title: Tri-City Education Connections
theme: minima
collections:
  locations: 
    output: true
  collection:
    output: true
markdown: kramdown

baseurl: ""
include:
  - "assets"

defaults:
  - scope:
      type: "collection"
    values:
      layout: collection_item
