title: Colin O'Brien's LIS786 Project
theme: minima
collections:
  locations: 
    output: true
  collection:
    output: true


defaults:
  - scope:
      type: "collection"
    values:
      layout: collection_item
